# Generated by Django 3.0.4 on 2020-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
