# Generated by Django 2.2.2 on 2019-07-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default='some', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profiles'),
        ),
    ]
