# Generated by Django 3.0.3 on 2020-03-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
