# Generated by Django 3.0.3 on 2020-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='no-video', null=True, upload_to='videos/'),
        ),
    ]
