# Generated by Django 3.0.3 on 2020-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_comment_in_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
