# Generated by Django 3.0.3 on 2020-03-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='last_name',
            new_name='surname',
        ),
    ]
